### ISSUE TITLE
[question] Getting the cookies from onAuth 

### ISSUE THREAD

**Issue by endel** [virtualcommons/port-of-mars#303]
Hi @cpritcha,

Here's how I believe you can grab the cookies from the `onAuth` method:

```typescript
import cookie from "cookie";

class MyRoom extends Room {

    onAuth(client, options, request) {
        const cookies = cookie.parse(request.headers.cookie);
        console.log("All cookies =>", cookies);
    }

}
```

Let me know if that works for you! Cheers!

**Comment by alee** [comment]
Thanks @endel ! We're trying to support both passport-cas and local development / testing authentication strategies. Since we using passport and passport / express sessions, we were hoping that it would be possible to figure out some way to have Colyseus authentication with the passport session.

Based on [this discussion](https://discuss.colyseus.io/topic/139/persistent-sessions/5) it seems we would need a cookie or token on the client side that we can use to verify the auth. Originally we were doing this via manual JWT creation - is it possible to have Colyseus integration with passport so that the client-side session cookie set by passport is used to perform the onAuth check instead? So it would use something like https://www.npmjs.com/package/express-session#storegetsid-callback to retrieve the session from the session store, then check if the session contains a valid authenticated user. I'm not sure if this is the right way to go about this, any input / suggestions would be much appreciated!

**Comment by endel** [comment]
Hi @alee, this does make sense. I'm experimenting with `express-session` right now, and this is the first iteration I've came up with. It looks very workaround-ish atm:

```typescript
import session from "express-session";
const sessionParser = session({ secret: "xxx" });

// ... setup express
app.use(sessionParser);

const gameServer = new Server({
  // ... colyseus configs
  verifyClient: (info, next) => {
    // use the same sessionParser for the WebSocket request
    sessionParser(info.req as any, {} as any, () => next(true));
  }
});
```

```typescript
// ... colyseus Room
  onAuth(client: Client, options: any, request: http.IncomingMessage) {
    const session = (request as any).session;
    console.log("SESSION =>", session);
    return true;
  }
```

(Haven't tried with Redis yet, hopefully works the same!)

**Comment by endel** [comment]
Hey, I've added a demo for this here https://github.com/endel/colyseus-express-session

Let me know if that works for you!

**Comment by cpritcha** [comment]
The `verifyClient` calling off to `sessionParser` worked. Thanks @endel!
