### ISSUE TITLE
subtract 25 system health at the beginning of the first round

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#527]

**Comment by chrstngyn** [comment]
would it be sufficient to set GameState upkeep default to 75? @cpritcha @alee 

`server/src/rooms/game/state/index.ts`
![image](https://user-images.githubusercontent.com/8737685/83079744-58178700-a031-11ea-8d05-83d9f5d1ee99.png)

**Comment by cpritcha** [comment]
Maybe we should have an explicit `end-of-round` phase where we make all players see in detail what impact group decisions had on their overall upkeep level in that round? Then we transition them to the investment or mars event phases based on whether or not it's the first round (we start off in round 0). This would also deal with our issue of not emphasizing the changes in upkeep level enough compared to the card game.

**Comment by chrstngyn** [comment]
i think this discussion may be more relevant to #531. that solution seems reasonable but what are the advantages of implementing an `end-of-round` phase vs creating a modal on the front end that appears at the beginning of the events phase? in the first round of the game, they wouldn't see the system health report until all actions have been finalized in the discard phase so this system health report wouldn't appear until the beginning of the next round. 

more relevant to this particular issue, I think it would be reasonable to set the default system health to 75 if -25 system health is subtracted at the start of the first round due to wear and tear

**Comment by cpritcha** [comment]
> i think this discussion may be more relevant to #531. that solution seems reasonable but what are the advantages of implementing an end-of-round phase vs creating a modal on the front end that appears at the beginning of the events phase?

Currently the mars event phase is tied to a particular mars event. Since we don't have any mars events in the first round we can't have a mars event phase.

> in the first round of the game, they wouldn't see the system health report until all actions have been finalized in the discard phase so this system health report wouldn't appear until the beginning of the next round.

If we start in the `end-of-round` Then players would get a summary of how their upkeep will change. Upon exit of the `end-of-round` phase an `entered-new-round` event can applied to the game state which updated the system health, mars events etc.

> more relevant to this particular issue, I think it would be reasonable to set the default system health to 75 if -25 system health is subtracted at the start of the first round due to wear and tear

I think it is important for comprehension that players understand the impact of their system health investment on the environment and how their personal investment decisions impact health. If we start at 75 health then we're not emphasizing role of player investments on system health. It was 100 but because no players invested into a time blocks into system health now only 75 health remains. It feels more urgent if players see upkeep change at the beginning of the game instead of starting at 75.

**Comment by alee** [comment]
Wouldn't we want a `begin-round` phase instead to support #531 ? end-of-round doesn't capture the initial system health update in the first round or we'd have to special case it out.

> Maybe we should have an explicit `end-of-round` phase where we make all players see in detail what impact group decisions had on their overall upkeep level in that round? Then we transition them to the investment or mars event phases based on whether or not it's the first round (we start off in round 0). This would also deal with our issue of not emphasizing the changes in upkeep level enough compared to the card game.

**Comment by cpritcha** [comment]
Transitioning out of the `end-of-round` phase in the `SetNextPhase` command would emit an `NewRoundInitialized` event which would update the state. The `NewRoundInitialized` event could take as an argument the amount of player contributed system health (or we could have server contributed health as part of the game state).
