### ISSUE TITLE
feedback on game_event.csv

### ISSUE THREAD

**Issue by MarcoAJanssen** [virtualcommons/port-of-mars#532]
We looked at the game_event.csv data and a number of issues came up:
“upkeep” needs to be “system health”
“system health” needs to be saved after updates during a game
Add a column that indicates the round of the game
Mars events are not filled in, so we do not collect data on which events happen.
Is information on time invested saved at the moment a player clicks on being ready? What happens if the player changes investment allocation after clicking being ready? We need to make sure the right information is saved.

There are events that lead players to loose influence cards. This is now listed as type is “time-investment” but it should be “influence-lost”
If there is voluntary philanthropy we do not see the elected player investing any timeblocks into “upkeep / system health”. This should be all their time blocks

We would like to have some changes to the data structure to make it more manageable to extract relevant data during the tournament and have the following columns
Id
Gameid
Round [new]
Type
Player [new, could be “all” if it is not a specific player”
Datecreated
Timeremaining
Action [instead of payload]

We also like to add the following types of actions:
Investphase-end
Tradephase-end
Purhasephase-end
Discardphase-end
Those are the number of seconds left when the fifth person is ready. We use this to calculate the duration of the phases and identify outlier groups.

Systemhealth-update, everytime system health is updated after an event, or investment.
Victory points, the number of points of the player at the end of a round

We would like to save data of time-invested instead of 

972,18,time-invested,"{""role"": ""Entrepreneur"", ""investment"": {""legacy"": 0, ""upkeep"": 0, ""culture"": 0, ""finance"": 5, ""science"": 0, ""government"": 0}}",2020-05-15 22:20:12.845,246

In the following way

972,18,1,time-invested, Entrepreneur, 2020-05-15 22:20:12.845,246, "legacy": 0: "upkeep": 0: "culture": 0: "finance": 5: "science": 0: "government": 0

**Comment by cpritcha** [comment]
> We also like to add the following types of actions:
> Investphase-end
> Tradephase-end
> Purhasephase-end
> Discardphase-end
> Those are the number of seconds left when the fifth person is ready. We use this to calculate the duration of the phases and identify outlier groups.

> Systemhealth-update, everytime system health is updated after an event, or investment.
Victory points, the number of points of the player at the end of a round

Adding artificial end of phase events is doable but I think the data would be easier to analyze if added additional columns were added  to the CSV export instead. I could record final phase information there such as final system health and victory points. Adding special `systemhealth-update` events would be error prone since I'd manually have to track what game events mutate the state. Alternatively, I could add a column the export csv that reports the what the system health is whenever an update occurs (then you manually check that that makes sense looking the corresponding event type and action).

How about I export the following CSVs to facilitate checking of what I think the state is given the applied events:

#### Game Event CSV

| column       | description                                 |
|----------------|-------------------------------------------|
| id               | event id created by db                |
| gameId      | game id associated with event   |
| round         | current round of game                |
| phase        | current phase of game  |
| marsEventsActiveCount | number of active mars events in the current round |
| marsEventsAppliedCount | number of mars events applied in the current round |
| timeRemaining | number of seconds remaining in phase |
| type           | name of event applied                 |
| player     | player that performed the action    |
| action     | json payload of event                     |
| phaseInitialTimeRemaining | time remaining at start of phase |
| phaseFinalTimeRemaining | time remaining at end of phase |
| phaseFinalSystemHealth | system health at end of phase |
| systemHealthInitial | system health before event application |
| systemHealthFinal | system health after event application |

#### Game Event Player Victory Points CSV

| column           | description                     |
|-------------------|---------------------------------|
| gameEventId | associated game event | 
| role | role for player |
| phaseFinalVictoryPoints | number of victory points currently possessed by a player |

#### Game Event Player Investments CSV

| column           | description                     |
|-------------------|---------------------------------|
| gameEventId | associated game event | 
| role                | role for player                |
| resource        | resource invested in such as legacy, culture, system health etc |
| amount          | units blocks invested in resource |
| cost               | cost in time blocks of resource |

#### Game Active Mars Events CSV

| column           | description                     |
|-------------------|---------------------------------|
| gameId          | associated game | 
| round             | round of game     |
| name             | mars event name |
| description     | mars event description |
| index              | mars event order of application (related to marsEventAppliedCount in the Game Event CSV file) |

This should enable validating the game state transitions.

> We would like to save data of time-invested instead of
>
> 972,18,time-invested,"{""role"": ""Entrepreneur"", ""investment"": {""legacy"": 0, ""upkeep"": 0, ""culture"": 0, ""finance"": 5, ""science"": 0, ""government"": 0}}",2020-05-15 22:20:12.845,246
>
> In the following way
>
> 972,18,1,time-invested, Entrepreneur, 2020-05-15 22:20:12.845,246, "legacy": 0: "upkeep": 0: "culture": 0: "finance": 5: "science": 0: "government": 0

I don't see how this would help analysis of the data since this would require having different schemas for each row based on the event type. Instead it would easier to analyze with multiple csv exports for one event table. See my above export suggestions for details.

**Comment by MarcoAJanssen** [comment]
Those csvs look promising. We will have to check. The files we got from the pretest 2 weeks ago contained insufficient to recreate what happened, so with more info on system health and events, and a special file with investments, this would be an improvement. Thanks!
