### ISSUE TITLE
User.dateCreated reset to 2021-01-29

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#670]
For some reason 333 of our User.dateCreated fields were set to `2021-01-29 23:21:..` or later

Perhaps `CreateDateColumn` gets touched whenever a database migration happens? Whatever the reason, it is not a Good Thing if our CreateDateColumns get updated everytime we run a data migration.

**Comment by cpritcha** [comment]
I don't see users before that time. If we accidentally reverted https://github.com/virtualcommons/port-of-mars/blob/main/server/src/migration/1607117297405-UserMetadataAddition.ts then that would have caused it since that removes the `dateCreated` field. The migrations table doesn't have a timestamp of when it was applied but reverting the is bot migration and remigrating did not impact the 1dateCreated` field (but reverting the migration that added dateCreated field resulted in `now()` values for all rows in the user table.

**Comment by alee** [comment]
That's the likely cause, just wanted to make sure it wasn't an accident - thanks for looking into it!
